name       : fakeroot
version    : '1.21'
release    : 8
source     :
    - http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.21.orig.tar.gz : 5d293c1b3604b2a9265d1811a9890c749887ef08aec55f3237d32bf35836171a
license    : GPL-2.0
summary    : Tool for simulating superuser privileges
description: |
    Tool for simulating superuser privileges
emul32     : yes
builddeps  :
    - acl-devel
    - acl-32bit-devel
    - attr-devel
    - attr-32bit-devel
    - libcap2-devel
    - libcap2-32bit-devel
    - po4a
rundeps    :
    - libcap2
    - 32bit :
        - libcap2-32bit
component  :
    - system.devel
setup      : |
    %apply_patches
    ./bootstrap
    %configure --disable-static \
               --with-ipc=sysv \
               --libdir=%libdir%/libfakeroot \
               --disable-dependency-tracking
    pushd doc
    po4a -k 0 --rm-backups --variable "srcdir=../doc/" po4a/po4a.cfg
    popd
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install -j1
    install -d -D -m 00755 $installdir/usr/share/ld.so.conf.d
    echo "%libdir%/libfakeroot" >> $installdir/usr/share/ld.so.conf.d/fakeroot.conf
