name       : fakeroot
version    : 1.20.2
release    : 7
source     :
    - http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.20.2.orig.tar.bz2 : 7c0a164d19db3efa9e802e0fc7cdfeff70ec6d26cdbdc4338c9c2823c5ea230c
license    : GPL-2.0
summary    : Tool for simulating superuser privileges
description: |
    Tool for simulating superuser privileges
emul32      : yes
builddeps  :
    - acl-devel
    - acl-32bit-devel
    - attr-devel
    - attr-32bit-devel
    - libcap2-devel
    - libcap2-32bit-devel
rundeps    :
    - libcap2
    - 32bit:
        - libcap2-32bit
component  :
    - system.devel
setup      : |
    %apply_patches
    ./bootstrap
    %configure --disable-static \
               --with-ipc=sysv \
               --libdir=%libdir%/libfakeroot
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
    install -d -D -m 00755 $installdir/usr/share/ld.so.conf.d
    echo "%libdir%/libfakeroot" >> $installdir/usr/share/ld.so.conf.d/fakeroot.conf
