name       : fakeroot
version    : '1.23'
release    : 11
source     :
    - https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.23.orig.tar.xz : 009cd6696a931562cf1c212bb57ca441a4a2d45cd32c3190a35c7ae98506f4f6
license    : GPL-3.0-or-later
summary    : Tool for simulating superuser privileges
description: |
    Tool for simulating superuser privileges
emul32     : yes
builddeps  :
    - acl-devel
    - acl-32bit-devel
    - attr-devel
    - attr-32bit-devel
    - libcap2-devel
    - libcap2-32bit-devel
    - po4a
rundeps    :
    - libcap2
    - 32bit :
        - libcap2-32bit
component  :
    - system.devel
setup      : |
    # Help with musl builds
    export CFLAGS="${CFLAGS/-D_FORTIFY_SOURCE=2/}"
    %apply_patches
    ./bootstrap
    %configure --disable-static \
               --with-ipc=sysv \
               --libdir=%libdir%/libfakeroot \
               --disable-dependency-tracking
    pushd doc
    po4a -k 0 --rm-backups --variable "srcdir=../doc/" po4a/po4a.cfg
    popd
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install -j1
    install -d -D -m 00755 $installdir/usr/share/ld.so.conf.d
    echo "%libdir%/libfakeroot" >> $installdir/usr/share/ld.so.conf.d/fakeroot.conf
